refactor: extract common code and extract to file

diff --git a/scripts/bin/replace b/scripts/bin/replace
--- a/scripts/bin/replace
+++ b/scripts/bin/replace
@@ -5,7 +5,11 @@
 #   replace old_term new_term
 #   replace -w old_term new_term # Whole word match only.
 
-exclude_dirs={.angular,.eggs,.git,.idea,.pytest_cache,.ruff_cache,.tox,__pycache__,build,env,env_*,htmlcov,node_modules}
+if [ ! -f ~/.config/dotfiles/exclude_dirs ]; then
+    echo "[ERROR] ~/.config/dotfiles/exclude_dirs not found"
+    exit 1
+fi
+. ~/.config/dotfiles/exclude_dirs
 
 is_whole_word_match=false
 if [ "$1" == "-w" ]; then
