feat(keepass): update

diff --git a/scripts/runs/keepass b/scripts/runs/keepass
--- a/scripts/runs/keepass
+++ b/scripts/runs/keepass
@@ -1,5 +1,43 @@
 #!/bin/bash
 
-set -e # Exit if any command fails.
+set -e
 
-sudo apt install -y keepassxc
+dry_run="0"
+
+while [[ $# -gt 0 ]]; do
+    echo "ARG: \"$1\""
+    if [[ "$1" == "--dry" ]]; then
+        dry_run="1"
+    fi
+    shift
+done
+
+log() {
+    if [[ $dry_run == "1" ]]; then
+        echo "[DRY_RUN] $@"
+    else
+        echo "[DEBUG] $@"
+    fi
+}
+
+execute() {
+    log "execute $@"
+    if [[ $dry_run == "1" ]]; then
+        return
+    fi
+    "$@"
+}
+
+if [ "$(uname -s)" = "Linux" ]; then
+    if [ -f /etc/os-release ]; then
+        source /etc/os-release
+    fi
+    if [ "$ID" = "arch" ]; then
+        execute sudo pacman -S keepassxc
+    else
+        execute sudo apt install -y keepassxc
+    fi
+else
+    echo "[ERROR] Unsupported OS: $(uname -s)" >&2
+    exit 1
+fi
